// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2zss5x5xq2Cd80bX7oxvKVhgQI3Ca5c',
    appId: '1:997983126048:web:cd6b648a53f7c7b8207245',
    messagingSenderId: '997983126048',
    projectId: 'senior-citizen-app-ed49f',
    authDomain: 'senior-citizen-app-ed49f.firebaseapp.com',
    storageBucket: 'senior-citizen-app-ed49f.appspot.com',
    measurementId: 'G-V5XQS9NJDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjAt6f9qUgQUdtVZ2I-_zVhJEx_bCfZV8',
    appId: '1:997983126048:android:6af3f9ab1823b724207245',
    messagingSenderId: '997983126048',
    projectId: 'senior-citizen-app-ed49f',
    storageBucket: 'senior-citizen-app-ed49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUV1GK3Cndkw9C7t6lEuXQtK5mkFmnKY',
    appId: '1:997983126048:ios:f703cb79601691cb207245',
    messagingSenderId: '997983126048',
    projectId: 'senior-citizen-app-ed49f',
    storageBucket: 'senior-citizen-app-ed49f.appspot.com',
    iosClientId: '997983126048-e33ap59ki75545jk1mbol2buraleedvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorCitizenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNUV1GK3Cndkw9C7t6lEuXQtK5mkFmnKY',
    appId: '1:997983126048:ios:f703cb79601691cb207245',
    messagingSenderId: '997983126048',
    projectId: 'senior-citizen-app-ed49f',
    storageBucket: 'senior-citizen-app-ed49f.appspot.com',
    iosClientId: '997983126048-e33ap59ki75545jk1mbol2buraleedvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorCitizenApp',
  );
}
